# Imports

In [2]:
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# Load best models

In [3]:
# Load best rocket model
best_rocket_model = joblib.load("./eda_rocket/model/eda_rocket_model.pkl")

In [4]:
# Load best weasel model
best_weasel_model = joblib.load("./eda_weasel/model/eda_weasel_model1.pkl")

D:\Python310\lib\site-packages\numba\typed\typeddict.py:34: NumbaTypeSafetyWarning: unsafe cast from int64 to uint32. Precision may be lost.
  d[key] = value


In [5]:
# Load best shapelet model
best_shapelet_model = joblib.load("./eda_shapelet/model/eda_shapelet_model1.pkl")

# Organaize data for testing

In [6]:
test_data = pd.read_csv("eda_rocket/train_data/EDA_vlad_1_results.csv")
# Take segments id 19 to 58
test_data = test_data[380:1180]
test_data

Time rel [s]  Day rel [d] Time rel [hh:mm:ss] Date abs [yyyy-mm-dd]  \
380            380            0            00:06:20            2023-07-11   
381            381            0            00:06:21            2023-07-11   
382            382            0            00:06:22            2023-07-11   
383            383            0            00:06:23            2023-07-11   
384            384            0            00:06:24            2023-07-11   
...            ...          ...                 ...                   ...   
1175          1175            0            00:19:35            2023-07-11   
1176          1176            0            00:19:36            2023-07-11   
1177          1177            0            00:19:37            2023-07-11   
1178          1178            0            00:19:38            2023-07-11   
1179          1179            0            00:19:39            2023-07-11   

     Time abs [hh:mm:ss]  ActivityClass []  Altitude [m]  BodyPosition []  \
380             16:56:57               2.0     97.714295              5.0   
381             16:56:58               2.0     97.702249              5.0   
382             16:56:59               2.0     97.684459              5.0   
383             16:57:00               2.0     97.664046              5.0   
384             16:57:01               2.0     97.645544              5.0   
...                  ...               ...           ...              ...   
1175            17:10:12               1.0     99.016731              1.0   
1176            17:10:13               7.0     99.045522              1.0   
1177            17:10:14               7.0     99.092540              1.0   
1178            17:10:15               7.0     99.157696              1.0   
1179            17:10:16               7.0     99.241750              1.0   

      EdaArousalMean []  EdaSclMean [uS]  ...  InclinationRight [deg]  \
380        2.315570e-02         8.349160  ...               42.645281   
381        1.803368e-02         8.298571  ...               42.645281   
382        1.404464e-02         8.253473  ...               42.645281   
383        1.093798e-02         8.215360  ...               42.645281   
384        8.518505e-03         8.187131  ...               42.405239   
...                 ...              ...  ...                     ...   
1175       7.216300e-16         4.513154  ...               85.944887   
1176       5.620060e-16         4.512908  ...               85.753281   
1177       4.376910e-16         4.512259  ...               85.753281   
1178       3.408740e-16         4.513837  ...               85.753281   
1179       2.654730e-16         4.526789  ...               85.753281   

      MovementAcceleration [g]  NonWearTime []  StepCount [steps]  \
380                   0.004673             0.0                0.0   
381                   0.004744             0.0                0.0   
382                   0.003056             0.0                0.0   
383                   0.003090             0.0                0.0   
384                   0.005561             0.0                0.0   
...                        ...             ...                ...   
1175                  0.004095             0.0                0.0   
1176                  0.003471             0.0                0.0   
1177                  0.003090             0.0                0.0   
1178                  0.003929             0.0                0.0   
1179                  0.045095             0.0                0.0   

      TempMean []  VerticalSpeed [m/s]  temp [Grad Celsius]  Markers  \
380          29.0            -0.006225                 29.0      NaN   
381          29.0            -0.006348                 29.0      NaN   
382          29.0            -0.006390                 29.0      NaN   
383          29.0            -0.006052                 29.0      NaN   
384          29.0            -0.005315                 29.0      NaN   
...           ... 

In [7]:
Y_test = pd.read_csv("eda_rocket/train_data/EDA_vlad_1.csv")
# Take segments id 19 to 58
Y_test = Y_test[19:59]
Y_test

Segment id label
19          19    no
20          20    no
21          21    no
22          22    no
23          23    no
24          24    no
25          25    no
26          26    no
27          27    no
28          28    no
29          29    no
30          30    no
31          31    no
32          32    no
33          33    no
34          34    no
35          35    no
36          36    no
37          37    no
38          38    no
39          39    no
40          40   yes
41          41    no
42          42    no
43          43    no
44          44    no
45          45    no
46          46    no
47          47    no
48          48    no
49          49    no
50          50    no
51          51    no
52          52    no
53          53    no
54          54    no
55          55    no
56          56    no
57          57    no
58          58    no

In [8]:
label_encoder = LabelEncoder()
# Get the real labels of the testing data
test_encoded_labels = label_encoder.fit_transform(Y_test.label)
test_encoded_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
Y_test["encoded_label"] = test_encoded_labels
Y_test

Segment id label  encoded_label
19          19    no              0
20          20    no              0
21          21    no              0
22          22    no              0
23          23    no              0
24          24    no              0
25          25    no              0
26          26    no              0
27          27    no              0
28          28    no              0
29          29    no              0
30          30    no              0
31          31    no              0
32          32    no              0
33          33    no              0
34          34    no              0
35          35    no              0
36          36    no              0
37          37    no              0
38          38    no              0
39          39    no              0
40          40   yes              1
41          41    no              0
42          42    no              0
43          43    no              0
44          44    no              0
45          45    no              0
46          46    no              0
47          47    no              0
48          48    no              0
49          49    no              0
50          50    no              0
51          51    no              0
52          52    no              0
53          53    no              0
54          54    no              0
55          55    no              0
56          56    no              0
57          57    no              0
58          58    no              0

In [10]:
# Extract the measuremens columns as time series data
X_test = test_data.groupby('Segment id')['EdaArousalMean []'].apply(list).values
X_test_np = np.vstack(X_test)
X_test_np

array([[2.31556990e-02, 1.80336760e-02, 1.40446410e-02, 1.09379780e-02,
        8.51850500e-03, 6.63421900e-03, 5.16673500e-03, 4.02385700e-03,
        3.13378300e-03, 2.44059300e-03, 1.90073500e-03, 1.48029400e-03,
        1.15285400e-03, 8.97844000e-04, 6.99242000e-04, 5.44570000e-04,
        4.24111000e-04, 3.30298000e-04, 2.57237000e-04, 2.00336000e-04],
       [1.56022000e-04, 1.21510000e-04, 9.46320000e-05, 7.36995000e-05,
        5.73972000e-05, 4.47010000e-05, 3.48132000e-05, 2.71125000e-05,
        2.11153000e-05, 1.64446000e-05, 1.28071000e-05, 9.97414000e-06,
        7.76787000e-06, 6.04962000e-06, 4.71145000e-06, 3.66928000e-06,
        2.85764000e-06, 2.22553000e-06, 1.73325000e-06, 1.34985000e-06],
       [1.05127000e-06, 8.18728000e-07, 6.37626000e-07, 4.96583000e-07,
        3.86740000e-07, 3.01193000e-07, 2.34569000e-07, 1.82683000e-07,
        1.42274000e-07, 1.10803000e-07, 8.62933000e-08, 6.72053000e-08,
        5.23395000e-08, 1.57632450e-02, 3.03056237e-01, 2.4586

# Test models on Vlad's 1st experiment data

## Test best rocket model

In [18]:
# Print the real labels
test_encoded_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
y_pred_rocket = best_rocket_model.predict(X_test_np)
y_pred_rocket

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Calculate accuracy of the model on Vlad's 1st experiment data
accuracy_rocket = accuracy_score(test_encoded_labels, y_pred_rocket)
print(f"Accuracy: {accuracy_rocket * 100:.2f}%")
report_rocket = classification_report(test_encoded_labels, y_pred_rocket)
print(report_rocket)

Accuracy: 92.50%
              precision    recall  f1-score   support

           0       0.97      0.95      0.96        39
           1       0.00      0.00      0.00         1

    accuracy                           0.93        40
   macro avg       0.49      0.47      0.48        40
weighted avg       0.95      0.93      0.94        40



## Test best weasel model

In [13]:
y_pred_weasel = best_weasel_model.predict(X_test_np)
y_pred_weasel

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Calculate accuracy of the model on Vlad's 1st experiment data
accuracy_weasel = accuracy_score(test_encoded_labels, y_pred_weasel)
print(f"Accuracy: {accuracy_weasel * 100:.2f}%")
report_weasel = classification_report(test_encoded_labels, y_pred_weasel, zero_division=1)
print(report_weasel)

Accuracy: 97.50%
              precision    recall  f1-score   support

           0       0.97      1.00      0.99        39
           1       1.00      0.00      0.00         1

    accuracy                           0.97        40
   macro avg       0.99      0.50      0.49        40
weighted avg       0.98      0.97      0.96        40



## Test best shapelet model

In [15]:
y_pred_shapelet = best_shapelet_model.predict(X_test_np)
y_pred_shapelet

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# Calculate accuracy of the model on Vlad's 1st experiment data
accuracy_shapelet = accuracy_score(test_encoded_labels, y_pred_shapelet)
print(f"Accuracy: {accuracy_shapelet * 100:.2f}%")
report_shapelet = classification_report(test_encoded_labels, y_pred_shapelet)
print(report_shapelet)

Accuracy: 95.00%
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        39
           1       0.00      0.00      0.00         1

    accuracy                           0.95        40
   macro avg       0.49      0.49      0.49        40
weighted avg       0.95      0.95      0.95        40

